// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idjmabhvzupcdygguqzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkam1hYmh2enVwY2R5Z2d1cXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTk5MDEsImV4cCI6MjA3MDQ5NTkwMX0.Dep7HS-4EwRIa9vCXWdwC20ARnTvHoB-oyBPGRV3VAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});